// Interface automatically generated by schemas-to-ts

export interface Form {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    successMessage?: string;
    errorMessage?: string;
    submitUrl?: string;
    fields?: any;
  };
}
export interface Form_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  successMessage?: string;
  errorMessage?: string;
  submitUrl?: string;
  fields?: any;
}

export interface Form_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  successMessage?: string;
  errorMessage?: string;
  submitUrl?: string;
  fields?: any;
}

export interface Form_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  successMessage?: string;
  errorMessage?: string;
  submitUrl?: string;
  fields?: any;
}
