// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { Article } from '../../../article/content-types/article/article';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { Article_Plain } from '../../../article/content-types/article/article';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ArticleComment {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    text?: string;
    user?: { data: User };
    article?: { data: Article };
    isApproved?: boolean;
  };
}
export interface ArticleComment_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  user?: User_Plain;
  article?: Article_Plain;
  isApproved?: boolean;
}

export interface ArticleComment_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  user?: number;
  article?: number;
  isApproved?: boolean;
}

export interface ArticleComment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
  article?: AdminPanelRelationPropertyModification<Article_Plain>;
  isApproved?: boolean;
}
