// Interface automatically generated by schemas-to-ts

import { Header } from '../../../../components/layout/interfaces/Header';
import { Footer } from '../../../../components/layout/interfaces/Footer';
import { Header_Plain } from '../../../../components/layout/interfaces/Header';
import { Footer_Plain } from '../../../../components/layout/interfaces/Footer';
import { Header_NoRelations } from '../../../../components/layout/interfaces/Header';
import { Footer_NoRelations } from '../../../../components/layout/interfaces/Footer';

export interface Global {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    Header?: Header;
    Footer?: Footer;
  };
}
export interface Global_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  Header?: Header_Plain;
  Footer?: Footer_Plain;
}

export interface Global_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  Header?: Header_NoRelations;
  Footer?: Footer_NoRelations;
}

export interface Global_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  Header?: Header_Plain;
  Footer?: Footer_Plain;
}
