// Interface automatically generated by schemas-to-ts

export enum ButtonType {
  Primary = 'PRIMARY',
  Secondary = 'SECONDARY',}

export interface Button {
  text?: string;
  buttonType?: ButtonType;
}
export interface Button_Plain {
  text?: string;
  buttonType?: ButtonType;
}

export interface Button_NoRelations {
  text?: string;
  buttonType?: ButtonType;
}

