// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Link_Plain } from './Link';
import { Link_NoRelations } from './Link';

export interface LangList {
  Link: Link[];
}
export interface LangList_Plain {
  Link: Link_Plain[];
}

export interface LangList_NoRelations {
  Link: Link_NoRelations[];
}

