// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export enum ButtonType {
  Primary = 'PRIMARY',
  Secondary = 'SECONDARY',}

export interface Link {
  text?: string;
  url?: string;
  isExternal?: boolean;
  isButton?: boolean;
  buttonType?: ButtonType;
  isLogo?: boolean;
  image?: { data: Media };
  isAnchor?: boolean;
}
export interface Link_Plain {
  text?: string;
  url?: string;
  isExternal?: boolean;
  isButton?: boolean;
  buttonType?: ButtonType;
  isLogo?: boolean;
  image?: Media_Plain;
  isAnchor?: boolean;
}

export interface Link_NoRelations {
  text?: string;
  url?: string;
  isExternal?: boolean;
  isButton?: boolean;
  buttonType?: ButtonType;
  isLogo?: boolean;
  image?: number;
  isAnchor?: boolean;
}

