// Interface automatically generated by schemas-to-ts

import { Link } from '../../../../components/shared/interfaces/Link';
import { SharedSection } from '../../../shared-section/content-types/shared-section/shared-section';
import { Link_Plain } from '../../../../components/shared/interfaces/Link';
import { SharedSection_Plain } from '../../../shared-section/content-types/shared-section/shared-section';
import { Link_NoRelations } from '../../../../components/shared/interfaces/Link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Page_404 {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    link?: Link;
    shared_section?: { data: SharedSection };
  };
}
export interface Page_404_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  link?: Link_Plain;
  shared_section?: SharedSection_Plain;
}

export interface Page_404_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  link?: Link_NoRelations;
  shared_section?: number;
}

export interface Page_404_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  link?: Link_Plain;
  shared_section?: AdminPanelRelationPropertyModification<SharedSection_Plain>;
}
