// Interface automatically generated by schemas-to-ts

import { MenuFooter } from './MenuFooter';
import { MenuFooter_Plain } from './MenuFooter';
import { MenuFooter_NoRelations } from './MenuFooter';

export interface Footer {
  textTop?: string;
  textBottom?: string;
  copyright?: string;
  Menu?: MenuFooter;
}
export interface Footer_Plain {
  textTop?: string;
  textBottom?: string;
  copyright?: string;
  Menu?: MenuFooter_Plain;
}

export interface Footer_NoRelations {
  textTop?: string;
  textBottom?: string;
  copyright?: string;
  Menu?: MenuFooter_NoRelations;
}

