// Interface automatically generated by schemas-to-ts

import { Link } from '../../shared/interfaces/Link';
import { MenuMain } from './MenuMain';
import { LangList } from '../../shared/interfaces/LangList';
import { Link_Plain } from '../../shared/interfaces/Link';
import { MenuMain_Plain } from './MenuMain';
import { LangList_Plain } from '../../shared/interfaces/LangList';
import { Link_NoRelations } from '../../shared/interfaces/Link';
import { MenuMain_NoRelations } from './MenuMain';
import { LangList_NoRelations } from '../../shared/interfaces/LangList';

export interface Header {
  Logo?: Link;
  Menu?: MenuMain;
  LangList?: LangList;
}
export interface Header_Plain {
  Logo?: Link_Plain;
  Menu?: MenuMain_Plain;
  LangList?: LangList_Plain;
}

export interface Header_NoRelations {
  Logo?: Link_NoRelations;
  Menu?: MenuMain_NoRelations;
  LangList?: LangList_NoRelations;
}

