// Interface automatically generated by schemas-to-ts

import { Link } from '../../shared/interfaces/Link';
import { Link_Plain } from '../../shared/interfaces/Link';
import { Link_NoRelations } from '../../shared/interfaces/Link';

export interface MenuFooter {
  MenuLink: Link[];
}
export interface MenuFooter_Plain {
  MenuLink: Link_Plain[];
}

export interface MenuFooter_NoRelations {
  MenuLink: Link_NoRelations[];
}

