// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Seo {
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string;
  canonical?: string;
  ogType?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: { data: Media };
  structuredData?: string;
  noindex?: boolean;
  nofollow?: boolean;
}
export interface Seo_Plain {
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string;
  canonical?: string;
  ogType?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: Media_Plain;
  structuredData?: string;
  noindex?: boolean;
  nofollow?: boolean;
}

export interface Seo_NoRelations {
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string;
  canonical?: string;
  ogType?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: number;
  structuredData?: string;
  noindex?: boolean;
  nofollow?: boolean;
}

