// Interface automatically generated by schemas-to-ts

export interface FormSubmit {
  label?: string;
}
export interface FormSubmit_Plain {
  label?: string;
}

export interface FormSubmit_NoRelations {
  label?: string;
}

