// Interface automatically generated by schemas-to-ts

import { FormCheckboxesList } from './FormCheckboxesList';
import { FormCheckboxesList_Plain } from './FormCheckboxesList';
import { FormCheckboxesList_NoRelations } from './FormCheckboxesList';

export enum Type {
  Checkbox = 'checkbox',
  Radio = 'radio',}

export interface FormCheckboxes {
  label?: string;
  name?: string;
  type?: Type;
  items: FormCheckboxesList[];
}
export interface FormCheckboxes_Plain {
  label?: string;
  name?: string;
  type?: Type;
  items: FormCheckboxesList_Plain[];
}

export interface FormCheckboxes_NoRelations {
  label?: string;
  name?: string;
  type?: Type;
  items: FormCheckboxesList_NoRelations[];
}

