// Interface automatically generated by schemas-to-ts

import { FormSelectOptions } from './FormSelectOptions';
import { FormSelectOptions_Plain } from './FormSelectOptions';
import { FormSelectOptions_NoRelations } from './FormSelectOptions';

export interface FormSelect {
  label?: string;
  name?: string;
  placeholder?: string;
  isRequired?: boolean;
  options: FormSelectOptions[];
}
export interface FormSelect_Plain {
  label?: string;
  name?: string;
  placeholder?: string;
  isRequired?: boolean;
  options: FormSelectOptions_Plain[];
}

export interface FormSelect_NoRelations {
  label?: string;
  name?: string;
  placeholder?: string;
  isRequired?: boolean;
  options: FormSelectOptions_NoRelations[];
}

