// Interface automatically generated by schemas-to-ts

export interface FormSelectOptions {
  label?: string;
  value?: string;
}
export interface FormSelectOptions_Plain {
  label?: string;
  value?: string;
}

export interface FormSelectOptions_NoRelations {
  label?: string;
  value?: string;
}

