// Interface automatically generated by schemas-to-ts

export interface FormAgree {
  label?: string;
  name: string;
}
export interface FormAgree_Plain {
  label?: string;
  name: string;
}

export interface FormAgree_NoRelations {
  label?: string;
  name: string;
}

