// Interface automatically generated by schemas-to-ts

export enum Type {
  Text = 'text',
  Email = 'email',}

export interface FormInput {
  label?: string;
  name?: string;
  placeholder?: string;
  type?: Type;
  isRequired?: boolean;
}
export interface FormInput_Plain {
  label?: string;
  name?: string;
  placeholder?: string;
  type?: Type;
  isRequired?: boolean;
}

export interface FormInput_NoRelations {
  label?: string;
  name?: string;
  placeholder?: string;
  type?: Type;
  isRequired?: boolean;
}

