// Interface automatically generated by schemas-to-ts

export interface FormCheckboxesList {
  title?: string;
  value?: string;
  isChecked?: boolean;
}
export interface FormCheckboxesList_Plain {
  title?: string;
  value?: string;
  isChecked?: boolean;
}

export interface FormCheckboxesList_NoRelations {
  title?: string;
  value?: string;
  isChecked?: boolean;
}

