// Interface automatically generated by schemas-to-ts

export interface FormRequest {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    formTitle?: string;
    formData?: any;
  };
}
export interface FormRequest_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  formTitle?: string;
  formData?: any;
}

export interface FormRequest_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  formTitle?: string;
  formData?: any;
}

export interface FormRequest_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  formTitle?: string;
  formData?: any;
}
