// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Review {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    text?: string;
    rating?: number;
    isApproved?: boolean;
    user?: { data: User };
  };
}
export interface Review_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  rating?: number;
  isApproved?: boolean;
  user?: User_Plain;
}

export interface Review_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  rating?: number;
  isApproved?: boolean;
  user?: number;
}

export interface Review_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  rating?: number;
  isApproved?: boolean;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
}
