// Interface automatically generated by schemas-to-ts

import { TextSection } from '../../../../components/sections/interfaces/TextSection';
import { TextSection_Plain } from '../../../../components/sections/interfaces/TextSection';
import { TextSection_NoRelations } from '../../../../components/sections/interfaces/TextSection';

export interface TermsOfService {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    section?: TextSection;
  };
}
export interface TermsOfService_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  section?: TextSection_Plain;
}

export interface TermsOfService_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  section?: TextSection_NoRelations;
}

export interface TermsOfService_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  section?: TextSection_Plain;
}
