// Interface automatically generated by schemas-to-ts

import { Category } from '../../../category/content-types/category/category';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Seo } from '../../../../components/layout/interfaces/Seo';
import { ArticleComment } from '../../../article-comment/content-types/article-comment/article-comment';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Seo_Plain } from '../../../../components/layout/interfaces/Seo';
import { ArticleComment_Plain } from '../../../article-comment/content-types/article-comment/article-comment';
import { Seo_NoRelations } from '../../../../components/layout/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    description?: string;
    category?: { data: Category };
    image?: { data: Media };
    text?: any;
    seo?: Seo;
    article_comments: { data: ArticleComment[] };
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  description?: string;
  category?: Category_Plain;
  image?: Media_Plain;
  text?: any;
  seo?: Seo_Plain;
  article_comments: ArticleComment_Plain[];
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  description?: string;
  category?: number;
  image?: number;
  text?: any;
  seo?: Seo_NoRelations;
  article_comments: number[];
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  description?: string;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  text?: any;
  seo?: Seo_Plain;
  article_comments: AdminPanelRelationPropertyModification<ArticleComment_Plain>;
}
