// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface About {
  title?: string;
  description?: string;
  text?: any;
  image?: { data: Media };
}
export interface About_Plain {
  title?: string;
  description?: string;
  text?: any;
  image?: Media_Plain;
}

export interface About_NoRelations {
  title?: string;
  description?: string;
  text?: any;
  image?: number;
}

