// Interface automatically generated by schemas-to-ts

import { Gallery } from '../../../api/gallery/content-types/gallery/gallery';
import { Gallery_Plain } from '../../../api/gallery/content-types/gallery/gallery';

export interface GalleryComponent {
  title?: string;
  description?: string;
  gallery?: { data: Gallery };
}
export interface GalleryComponent_Plain {
  title?: string;
  description?: string;
  gallery?: Gallery_Plain;
}

export interface GalleryComponent_NoRelations {
  title?: string;
  description?: string;
  gallery?: number;
}

