// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Hero {
  title?: string;
  text?: string;
  image?: { data: Media };
}
export interface Hero_Plain {
  title?: string;
  text?: string;
  image?: Media_Plain;
}

export interface Hero_NoRelations {
  title?: string;
  text?: string;
  image?: number;
}

