// Interface automatically generated by schemas-to-ts

export interface Map {
  title?: string;
  description?: string;
}
export interface Map_Plain {
  title?: string;
  description?: string;
}

export interface Map_NoRelations {
  title?: string;
  description?: string;
}

