// Interface automatically generated by schemas-to-ts

export interface OpeningHours {
  title?: string;
  description?: string;
  left_column?: any;
  right_column?: any;
}
export interface OpeningHours_Plain {
  title?: string;
  description?: string;
  left_column?: any;
  right_column?: any;
}

export interface OpeningHours_NoRelations {
  title?: string;
  description?: string;
  left_column?: any;
  right_column?: any;
}

