// Interface automatically generated by schemas-to-ts

import { Form } from '../../../api/form/content-types/form/form';
import { Form_Plain } from '../../../api/form/content-types/form/form';

export interface Request {
  title?: string;
  description?: string;
  form?: { data: Form };
}
export interface Request_Plain {
  title?: string;
  description?: string;
  form?: Form_Plain;
}

export interface Request_NoRelations {
  title?: string;
  description?: string;
  form?: number;
}

