// Interface automatically generated by schemas-to-ts

export interface Reviews {
  title?: string;
  description?: string;
}
export interface Reviews_Plain {
  title?: string;
  description?: string;
}

export interface Reviews_NoRelations {
  title?: string;
  description?: string;
}

