// Interface automatically generated by schemas-to-ts

import { Link } from '../../shared/interfaces/Link';
import { Link_Plain } from '../../shared/interfaces/Link';
import { Link_NoRelations } from '../../shared/interfaces/Link';

export interface Services {
  title?: string;
  text?: string;
  link?: Link;
}
export interface Services_Plain {
  title?: string;
  text?: string;
  link?: Link_Plain;
}

export interface Services_NoRelations {
  title?: string;
  text?: string;
  link?: Link_NoRelations;
}

