// Interface automatically generated by schemas-to-ts

export interface TextSection {
  title?: string;
  description?: string;
  text?: any;
}
export interface TextSection_Plain {
  title?: string;
  description?: string;
  text?: any;
}

export interface TextSection_NoRelations {
  title?: string;
  description?: string;
  text?: any;
}

