// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/layout/interfaces/Seo';
import { Seo_Plain } from '../../../../components/layout/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/layout/interfaces/Seo';

export interface Homepage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    sections?: any;
    seo?: Seo;
  };
}
export interface Homepage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  sections?: any;
  seo?: Seo_Plain;
}

export interface Homepage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  sections?: any;
  seo?: Seo_NoRelations;
}

export interface Homepage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  sections?: any;
  seo?: Seo_Plain;
}
